server:
  internalPort: 5005
  externalPort: 5005
  runMode: debug
redis:
  host: localhost
  port: 6379
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dbName: test
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zap
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60
cors:
  allowOrigins: "*"