server:
  internalPort: 5005
  externalPort: 5005
  runMode: debug
redis:
  host: localhost
  port: 6379
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500